### ISSUE TITLE
Week/month ved leje

### ISSUE THREAD

**Issue by Sneglehuset** [mikkeltschentscher/sneglehuset.com#37]
leje per periode står some week/month
![skaermbillede 2018-07-02 kl 19 41 52](https://user-images.githubusercontent.com/40136715/42178273-02d32652-7e30-11e8-964e-7e01bdd859ff.png)
![skaermbillede 2018-07-02 kl 19 42 18](https://user-images.githubusercontent.com/40136715/42178294-18819966-7e30-11e8-892d-6a7598446f7e.png)
![image](https://user-images.githubusercontent.com/40136715/42178314-27505536-7e30-11e8-83e8-d64cad0e4a96.png)

**Comment by mikkeltschentscher** [comment]
#20
