### ISSUE TITLE
Glemte at spørge i går undskyld

### ISSUE THREAD

**Issue by Sneglehuset** [mikkeltschentscher/sneglehuset.com#40]
Husker det som om vi diskuterede, at vores udlejningsprodukter ikke skulle være listet under andre kategorier end lån og lej (for at undgå at en potentiel "jeg vil gerne købe" bliver afledt og tænker "hmmm jeg kunne jo også leje"). Men vi får jævnligt henvendelser fra kunder som er inde i en given kategori og leder efter leje (jf gennemgangen i går m søgninger når man er på vores side).

Spm er: Skal vi lægge (nogle, måske ikke alle eller måske netop alle) udlejningsprodukterne ind på kategorierne. I givet fald kan vi så styre "placeringen" så de bliver vist, men f.eks. på sidste side?

**Comment by mikkeltschentscher** [comment]
Alle udlejningprodukter får et lille badge hvor der står "Udlejning". Det betyder at i sagtens kan inkludere i andre kategorier også. Se issue #19 - denne bliver løst dér :-)

Vi kan ikke placere dem andereledes i kategorierne end efter dato og lagerstatus da dette overskriver alle sorteringer.
